const comments = [
  "This is an interesting link.",
  "Thanks for sharing!",
  "I saved this link too.",
  "Trash, utter trash.",
  "What did I do to deserve this?",
  "Bookmarked!",
  "Didn't you already post something like this?",
  "I liked reading this article.",
  "This is information I didn't know I needed.",
  "I read something similar on reddit.",
  "You need to take a break from the computer",
  "Why am I even here?",
  "More please!",
  "I found a similar link on google.com",
  "Cringe...",
  "This is great!",
  "I put this in my pocket.",
  "This made my cat laugh.",
  "Cool, thanks for sharing dawg.",
  "Worth a look! Thanks!",
  "kthnxbyeeeee",
  "OK BOOMER",
  "We should turn this link into a meme and sell t-shirts",
  "Interesting...",
  "I don't care what you say, Pluto is still a planet!",
  "I laughed, I cried, I clicked this link.",
  "Why day is it even?",
  "Your link inspired me to go back to school and get a CS degree!",
  "Let me google that for you...",
  "Good read.",
  "This was just okay.",
  "My cat and I like to gossip about you.",
  "Just stopped by to say hi",
  "This is my favorite!",
  "Coolio",
  "Testing, testing, 1, 2, 3",
  "HAHAHAHAHAHAHAHA",
  "ROFL",
  "teeeheeeeee",
  "Hey, you're really good at this",
  "This link makes me hungry",
  "Reading this makes me thirsty.",
  "Thinking about food...",
  "Okay!",
  "Good looking out brah",
  "I wish there was a random comment generator so I don't have to keep writing this stuff",
  "Lorem ipsum dolor sit amet",
  "Excepteur sint occaecat cupidatat non proident",
  "Et tu?",
  "¿Por qué o por qué?",
  "こんにちは",
  "これはすごくいい",
  "恐ろしい",
  "Hear me ROAR",
  "I need to read this again!",
  "Looks pretty bad, man",
  "People are just going crazy for this!",
  "#BlackLivesMatter"
];

module.exports = comments;
